from django.core.management.base import BaseCommand
from store.models import App
import random

SAMPLE_APPS = [
    {
        'app_name': 'Aether Strike: Mech Ops',
        'package_name': 'com.hadi88.aetherstrike',
        'developer_name': 'Hadi88 Studio',
        'category': 'Games',
        'description': 'Command heavy artillery bipedal walkers in 6v6 squad raids. High-speed tactical mech combat.',
        'version': '3.2.0',
        'file_size': '124 MB',
        'downloads_count': 2480500,
        'rating': 4.8,
        'is_featured': True,
    },
    {
        'app_name': 'Zenith Flow Workspace',
        'package_name': 'com.hadi88.zenithflow',
        'developer_name': 'Zenith Systems',
        'category': 'Productivity',
        'description': 'Privacy-first workspace combining markdown notes, task boards, and offline SQLite synchronization.',
        'version': '2.5.4',
        'file_size': '38 MB',
        'downloads_count': 890400,
        'rating': 4.9,
        'is_featured': True,
    },
    {
        'app_name': 'Cyber Strike: Neon Rush',
        'package_name': 'com.hadi88.cyberstrike',
        'developer_name': 'Hyperion Games',
        'category': 'Games',
        'description': 'Blaze through neon canyons in anti-gravity hovercrafts with realistic physics and controller mapping.',
        'version': '1.8.9',
        'file_size': '95 MB',
        'downloads_count': 1420100,
        'rating': 4.7,
        'is_featured': True,
    },
    {
        'app_name': 'Lunar Social Network',
        'package_name': 'com.hadi88.lunarnetwork',
        'developer_name': 'Lunar Labs',
        'category': 'Social',
        'description': 'A clean, privacy-respecting micro-community platform with zero targeted tracking or ad clutter.',
        'version': '4.1.2',
        'file_size': '42 MB',
        'downloads_count': 1950000,
        'rating': 4.6,
        'is_featured': True,
    },
    {
        'app_name': 'Pulse Audio DAW Studio',
        'package_name': 'com.hadi88.pulseaudio',
        'developer_name': 'Pulse Audio Tech',
        'category': 'Tools',
        'description': '32-track digital audio workstation on mobile. Record multi-mic instruments and sequence synths.',
        'version': '5.0.1',
        'file_size': '86 MB',
        'downloads_count': 520400,
        'rating': 4.9,
        'is_featured': False,
    },
    {
        'app_name': 'Chronos Habit Tracker',
        'package_name': 'com.hadi88.chronoshabits',
        'developer_name': 'Chronos Digital',
        'category': 'Productivity',
        'description': 'Scientifically designed habit builder with cognitive psychology routines and one-tap widgets.',
        'version': '2.1.0',
        'file_size': '22 MB',
        'downloads_count': 670200,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Forge Terminal SSH & SFTP',
        'package_name': 'com.hadi88.forgeterminal',
        'developer_name': 'Forge DevTools',
        'category': 'Tools',
        'description': 'Heavy-duty Unix terminal emulator, SSH2 client, and SFTP file transfer engine with tmux support.',
        'version': '3.7.8',
        'file_size': '28 MB',
        'downloads_count': 430100,
        'rating': 4.9,
        'is_featured': False,
    },
    {
        'app_name': 'Vanguard Tactical Chess',
        'package_name': 'com.hadi88.vanguardchess',
        'developer_name': 'Vanguard Games',
        'category': 'Games',
        'description': 'Chess reimagined through isometric battlefield aesthetics with Stockfish 17 evaluation.',
        'version': '2.0.4',
        'file_size': '64 MB',
        'downloads_count': 780900,
        'rating': 4.7,
        'is_featured': False,
    },
    {
        'app_name': 'Krypton Hardware Wallet',
        'package_name': 'com.hadi88.kryptonwallet',
        'developer_name': 'Krypton Security',
        'category': 'Finance',
        'description': 'Air-gapped biometric mobile vault and portfolio tracker with QR air-gap transaction signing.',
        'version': '1.9.3',
        'file_size': '34 MB',
        'downloads_count': 380200,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Spectra Raw Camera Pro',
        'package_name': 'com.hadi88.spectracamera',
        'developer_name': 'Spectra Optics',
        'category': 'Photography',
        'description': 'Full manual DSLR-grade mobile camera app with 14-bit DNG RAW capture and focus peaking.',
        'version': '3.4.1',
        'file_size': '56 MB',
        'downloads_count': 910000,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Apex Running & Biometrics',
        'package_name': 'com.hadi88.apexathletics',
        'developer_name': 'Apex Athletic Labs',
        'category': 'Health & Fitness',
        'description': 'Precision GPS telemetry, cadence analysis, VO2 Max, and heart rate recovery zone coaching.',
        'version': '4.3.0',
        'file_size': '48 MB',
        'downloads_count': 640000,
        'rating': 4.7,
        'is_featured': False,
    },
    {
        'app_name': 'Nebula Stream Player',
        'package_name': 'com.hadi88.nebulastream',
        'developer_name': 'Nebula Media Group',
        'category': 'Entertainment',
        'description': 'Universal media container with Dolby Vision HDR tone-mapping and SMB/DLNA streaming.',
        'version': '2.8.2',
        'file_size': '52 MB',
        'downloads_count': 1850300,
        'rating': 4.6,
        'is_featured': False,
    },
    {
        'app_name': 'Cipher Key Manager',
        'package_name': 'com.hadi88.cipherkeys',
        'developer_name': 'Cipher Guard',
        'category': 'Tools',
        'description': 'Zero-knowledge password manager and 2FA TOTP authenticator with Argon2id encryption.',
        'version': '3.1.5',
        'file_size': '18 MB',
        'downloads_count': 590800,
        'rating': 4.9,
        'is_featured': False,
    },
    {
        'app_name': 'Atlas Ledger Budgeting',
        'package_name': 'com.hadi88.atlasledger',
        'developer_name': 'Atlas Financial',
        'category': 'Finance',
        'description': 'Envelope budgeting and net-worth tracking with double-entry accounting and Sankey cash flows.',
        'version': '2.3.1',
        'file_size': '26 MB',
        'downloads_count': 410500,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Iron Forge Strength Log',
        'package_name': 'com.hadi88.ironforge',
        'developer_name': 'Barbell Science',
        'category': 'Health & Fitness',
        'description': 'Powerlifting and bodybuilding progressive overload tracker with 1RM and RPE calculations.',
        'version': '4.0.0',
        'file_size': '31 MB',
        'downloads_count': 730200,
        'rating': 4.9,
        'is_featured': False,
    },
    {
        'app_name': 'Shadow Realm RPG',
        'package_name': 'com.hadi88.shadowrealm',
        'developer_name': 'Valkyrie Interactive',
        'category': 'Games',
        'description': 'Immersive dark fantasy turn-based dungeon crawler with non-linear labyrinth battles.',
        'version': '1.5.7',
        'file_size': '110 MB',
        'downloads_count': 1640000,
        'rating': 4.7,
        'is_featured': False,
    },
    {
        'app_name': 'Vivid Darkroom Photo Editor',
        'package_name': 'com.hadi88.vividdarkroom',
        'developer_name': 'Vivid Imaging Studio',
        'category': 'Photography',
        'description': 'RAW photo color grading app with 3-way color wheels, film grain, and batch presets.',
        'version': '3.6.2',
        'file_size': '62 MB',
        'downloads_count': 830500,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Echo Podcasting & RSS',
        'package_name': 'com.hadi88.echopodcasts',
        'developer_name': 'Echo Media Labs',
        'category': 'Entertainment',
        'description': 'Open RSS podcast player with silence trimming, voice boost compression, and OPML support.',
        'version': '2.9.0',
        'file_size': '25 MB',
        'downloads_count': 610000,
        'rating': 4.7,
        'is_featured': False,
    },
    # Page 2 Apps (Apps 19 to 36)
    {
        'app_name': 'Quantum Code Editor',
        'package_name': 'com.hadi88.quantumeditor',
        'developer_name': 'Quantum Software',
        'category': 'Tools',
        'description': 'Lightweight code editor with Tree-sitter syntax highlighting and Git diff viewer.',
        'version': '2.2.4',
        'file_size': '30 MB',
        'downloads_count': 340900,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Prism Color Palette Studio',
        'package_name': 'com.hadi88.prismstudio',
        'developer_name': 'Prism UX Labs',
        'category': 'Tools',
        'description': 'Generate WCAG AA compliant accessible color palettes. Export directly to Tailwind CSS.',
        'version': '1.7.0',
        'file_size': '19 MB',
        'downloads_count': 280400,
        'rating': 4.9,
        'is_featured': False,
    },
    {
        'app_name': 'Overdrive Drift Rally',
        'package_name': 'com.hadi88.overdriverally',
        'developer_name': 'Torque Dynamics',
        'category': 'Games',
        'description': 'Realistic rally simulation with gravel, tarmac, manual clutch, and weather dynamics.',
        'version': '3.1.2',
        'file_size': '135 MB',
        'downloads_count': 1210000,
        'rating': 4.6,
        'is_featured': False,
    },
    {
        'app_name': 'Oasis Deep Focus & Noise',
        'package_name': 'com.hadi88.oasisfocus',
        'developer_name': 'Oasis Soundscapes',
        'category': 'Productivity',
        'description': 'Pink, brown, and green noise generator layered with binaural beats and rain recordings.',
        'version': '2.4.0',
        'file_size': '44 MB',
        'downloads_count': 510000,
        'rating': 4.9,
        'is_featured': False,
    },
    {
        'app_name': 'Nova Mind Meditation',
        'package_name': 'com.hadi88.novamind',
        'developer_name': 'Nova Mindfulness',
        'category': 'Health & Fitness',
        'description': 'Secular mindfulness, pranayama breathwork pacing, and sleep transition guides.',
        'version': '3.0.1',
        'file_size': '36 MB',
        'downloads_count': 490200,
        'rating': 4.8,
        'is_featured': False,
    },
    {
        'app_name': 'Stellar Sky Chart AR',
        'package_name': 'com.hadi88.stellarsky',
        'developer_name': 'Stellar Labs',
        'category': 'Entertainment',
        'description': 'Point camera at night sky to identify constellations, planets, and ISS flyover orbits.',
        'version': '4.5.0',
        'file_size': '72 MB',
        'downloads_count': 1450000,
        'rating': 4.8,
        'is_featured': False,
    }
]

class Command(BaseCommand):
    help = 'Seeds initial 24+ apps into Hadi88 Apps database for 18-items-per-page testing'

    def handle(self, *args, **options):
        created_count = 0
        for data in SAMPLE_APPS:
            app, created = App.objects.get_or_create(
                package_name=data['package_name'],
                defaults=data
            )
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Successfully seeded {created_count} apps! Total in database: {App.objects.count()} apps."
        ))
