# Generated by Django 5.1.15 on 2026-10-05 04:02

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150, verbose_name='Application Name')),
                ('package_name', models.SlugField(max_length=150, unique=True, verbose_name='Package Name (Slug)')),
                ('developer_name', models.CharField(default='Hadi88 Studio', max_length=120, verbose_name='Developer Name')),
                ('category', models.CharField(choices=[('Games', 'Games'), ('Productivity', 'Productivity'), ('Tools', 'Tools'), ('Social', 'Social'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Photography', 'Photography'), ('Health & Fitness', 'Health & Fitness')], db_index=True, default='Tools', max_length=50)),
                ('app_icon', models.ImageField(upload_to=store.models.app_icon_upload_path, verbose_name='App Icon (512x512)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=store.models.app_banner_upload_path, verbose_name='Featured Banner (16:9)')),
                ('description', models.TextField(verbose_name='Full Description')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('apk_file', models.FileField(upload_to=store.models.apk_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk', 'xapk', 'zip'])], verbose_name='APK Binary Package')),
                ('file_size', models.CharField(default='25 MB', max_length=20, verbose_name='File Size (e.g. 45 MB)')),
                ('downloads_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total Downloads')),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating (1.00 - 5.00)')),
                ('is_featured', models.BooleanField(default=False, help_text='Showcase in hero carousel')),
                ('is_published', models.BooleanField(default=True, help_text='Publicly visible in store')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-downloads_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('contact_method', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram')], default='Email', max_length=20)),
                ('contact_handle', models.CharField(blank=True, max_length=100, verbose_name='Phone / Username Handle')),
                ('app_title', models.CharField(max_length=150, verbose_name='Dreaming App Concept Title')),
                ('platform', models.CharField(choices=[('Android', 'Android (APK)'), ('iOS', 'iOS (Swift)'), ('Cross-Platform', 'Cross-Platform (Flutter / React Native)'), ('Web App', 'Web Application / PWA')], default='Android', max_length=30)),
                ('category', models.CharField(choices=[('Games', 'Games'), ('Productivity', 'Productivity'), ('Tools', 'Tools'), ('Social', 'Social'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Photography', 'Photography'), ('Health & Fitness', 'Health & Fitness')], default='Productivity', max_length=50)),
                ('requirements', models.TextField(verbose_name='Detailed App Requirements & Workflows')),
                ('timeline', models.CharField(default='2-4 Weeks', max_length=50, verbose_name='Desired Delivery Timeline')),
                ('budget', models.CharField(default='$1,000 - $3,000', max_length=50, verbose_name='Estimated Budget')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('In Development', 'In Development'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=30)),
                ('legal_policy_agreed', models.BooleanField(default=False, help_text='User strictly affirmed that requested app contains no illegal, pirated, or theft material.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client App Demand',
                'verbose_name_plural': 'Client App Demands',
                'ordering': ['-created_at'],
            },
        ),
    ]
