# Generated by Django 5.1 on 2026-10-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Reviewer Name')),
                ('user_avatar', models.URLField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Star Rating (1-5)')),
                ('comment', models.TextField(verbose_name='User Review')),
                ('device_model', models.CharField(blank=True, default='Android Device', max_length=100)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='store.app')),
            ],
            options={
                'verbose_name': 'App Review',
                'verbose_name_plural': 'App Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
