# Generated by Django 5.1 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_appreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='package_name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Package Name (e.g. com.hadi88.app)'),
        ),
    ]
